ALTER TABLE menu_items
  ADD COLUMN IF NOT EXISTS min_qty DECIMAL(10,2) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS max_qty DECIMAL(10,2) NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS step_qty DECIMAL(10,2) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS round_off_rule VARCHAR(40) NOT NULL DEFAULT 'nearest_0_50',
  ADD COLUMN IF NOT EXISTS service_charge_percent DECIMAL(6,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS price_override_role VARCHAR(40) NOT NULL DEFAULT 'manager_only',
  ADD COLUMN IF NOT EXISTS allow_open_price BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS hide_cost_on_pos BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS combo_eligible BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS weekend_price_rule BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS promotion_label VARCHAR(80);

ALTER TABLE menu_item_addons
  ADD COLUMN IF NOT EXISTS cost DECIMAL(10,2) NOT NULL DEFAULT 0;
